AllCops:
  Exclude:
    - lib/lineinput.rb
    - lib/uuid.rb

inherit_from: .rubocop_todo.yml

Lint/BlockAlignment:
  Enabled: true

Lint/EndAlignment:
  Enabled: AlignWith

Performance/ReverseEach:
  Enabled: true





