AllCops:
  Exclude:
    - lib/lineinput.rb
    - lib/uuid.rb
  DisplayCopNames: true

inherit_from: .rubocop_todo.yml

Lint/BlockAlignment:
  Enabled: true

Lint/EndAlignment:
  Enabled: AlignWith

Lint/EmptyWhen:
  Enabled: false

Performance/ReverseEach:
  Enabled: true

# Unnecessary spacing detected.
Style/ExtraSpacing:
  Enabled: true

# Use tr instead of gsub.
Performance/StringReplacement:
  Enabled: false

Performance/RangeInclude:
  Enabled: false

# Use alias_method instead of alias.
Style/Alias:
  EnforcedStyle: prefer_alias_method
  Enabled: true

# Do not introduce global variables.
Style/GlobalVars:
  Enabled: true

# Use self-assignment shorthand +=.
Style/SelfAssignment:
  Enabled: true

# When defining the == operator, name its argument other.
Style/OpMethod:
  Enabled: true

# Use snake_case for variable names.
Style/VariableName:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison
  Enabled: true

Style/TernaryParentheses:
  Enabled: false

Style/VariableNumber:
  EnforcedStyle: normalcase
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  Enabled: true

MultilineMethodCallBraceLayout:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
  Enabled: true

Style/HashSyntax:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: indent
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Enabled: true

Style/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  Enabled: true

Style/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  Enabled: true

##################### Metrics ##################################

Metrics/ClassLength:
  Max: 1500

Metrics/LineLength:
  Max: 256
  Exclude:
    - "test/**/*"

### should be < 50
Metrics/MethodLength:
  Max: 100
  Exclude:
    - "bin/review-*"
    - "test/**/*"

### should be < 20
Metrics/CyclomaticComplexity:
  Max: 32

### should be < 60
Metrics/AbcSize:
  Max: 120
  Exclude:
    - "bin/review-*"
    - "test/**/*"

### shoud be < 25
Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
