AllCops:
  Exclude:
    - lib/lineinput.rb
    - lib/uuid.rb

inherit_from: .rubocop_todo.yml

Lint/BlockAlignment:
  Enabled: true

Lint/EndAlignment:
  Enabled: AlignWith

Performance/ReverseEach:
  Enabled: true

# Unnecessary spacing detected.
Style/ExtraSpacing:
  Enabled: true

# Use tr instead of gsub.
Performance/StringReplacement:
  Enabled: false

# Use alias_method instead of alias.
Style/Alias:
  Enabled: true
